### ISSUE TITLE
Add Post Request "Received Simulation" #1

### ISSUE THREAD

**Issue by mVeerasingam** [mVeerasingam/BatterySimulator-JobManager#1]
We can update the simulation parameters through Java.
However we should be able just receive the result data to be logged in the database. "id" and "results".

Id = simulation id, this will be generated from the database
result = result of simulation data

The prototype has a file named flask_simulation_finished.py
The java should be of same function.
https://github.com/MarkVeerasingam/PyBaMM_BatterySimulator_Prototype/commit/d6e100b00054a07dd3ebd7a1aaa99db1c2f6877f

**Comment by LucasJeanes** [comment]
Done and done. QueueService now assigns the unique id (Not the most technical method but it works). Bonus is we can send that unique ID back to the user in Talend when they send the simulation input to rabbit. With their ID for that simulation they can use the other endpoint and retrieve their results.
